### ISSUE TITLE
CodePipelineServiceRole:Resource creation cancelled

### ISSUE THREAD

**Issue by amal-v** [microservices-today/ngp-codepipeline#47]
```
Invalid principal in policy: com.amazon.balsa.error.InvalidPolicyException: The passed in policy has a statement with no principals!
```
Happens when running in development mode. Need a better implementation for 
```
Principal:
                AWS:
                  - !If [IsProductionCondition, !Sub "arn:aws:iam::${SourceECSAWSAccountId}:root", !Ref "AWS::NoValue"]
              Action:
                - "sts:AssumeRole"
```
